import type { NextPage } from 'next';
import Head from 'next/head';
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import styles from '../styles/Home.module.css';
import { FC } from 'react';

type Props = {
  products: [];
};

const Home: FC<Props> = ({ products }) => {
  console.log(products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App with Strapi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
};

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'http://localhost:1337/graphql',
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query getProducts {
        products {
          data {
            attributes {
              variants {
                colors {
                  id
                }
              }
            }
          }
        }
      }
    `,
  });

  return {
    props: {
      products: data.products,
    },
  };
}

export default Home;
